### ISSUE TITLE
Fix the Matlab DataONE Client testPublish() test

### ISSUE THREAD

**Issue by csjx** [DataONEorg/sem-prov-design#177] opened 2015-10-17 03:24 UTC
The testPublish() test doesn't make any assertions about the round trip success of the uploads.  Assert that uploads have succeeded.  There's also an issue of repeatedly using the same file names across runs, so identifier conflicts will cause the test to fail.  fix this in the RunManager implementation.

**Comment by sycao5** [comment] 2015-11-03 16:55
The publish( ) methods works on macOS, but not working on linux OS. The error information received is attached below.


K>> mgr.publish('2c2f8860-a6c5-4622-bcc8-5a316f049b47');
Undefined variable "mgr" or class "mgr.publish".
 
Error using org.dataone.client.run.RunManager/publish (line 1995)
Could not create member node reference: Java exception occurred:
org.dataone.service.exceptions.ServiceFailure: class org.dataone.client.exception.ClientSideException: Error: The CnList has not been
initialized!!!
	at org.dataone.client.v2.impl.NodeListNodeLocator.getCNode(NodeListNodeLocator.java:97)
	at org.dataone.client.v2.impl.NodeListNodeLocator.getCNode(NodeListNodeLocator.java:54)
	at org.dataone.client.v2.itk.D1Client.getCN(D1Client.java:127)
	at org.dataone.client.v2.itk.D1Client.getCN(D1Client.java:96)
	at org.dataone.client.v2.itk.D1Client.getMN(D1Client.java:243)
Caused by: org.dataone.client.exception.ClientSideException: Error: The CnList has not been initialized!!!
	... 5 more

**Comment by csjx** [comment] 2016-01-27 15:41
The testPublish() test works (duplicate id was resolved months ago).  However, we still need for the round trip success to be tested via assertions.

**Comment by sycao5** [comment] 2016-05-11 18:31
The publish() function works and I close this issue.

**Closed by sycao5** 2016-05-11 18:31 UTC
Labels: matlab-dataone, provenance, task
